config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books, only: [:index, :show, :update]
  resources :book_authors, only: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :birth_year, presence: true, numericality: {only_integer: true, less_than_or_equal_to: Time.now.year}

  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors

  def name_and_birthyear
    "#{self.name} (b. #{self.birth_year})"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :authors, through: :book_authors
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book

  validates_uniqueness_of :book, scope: :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(params.require(:author).permit(:name, :birth_year))
    if @author.valid?
      redirect_to @author
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(params.require(:author).permit(:name, :birth_year))
      @author.save
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    Author.find(params[:id]).destroy
    redirect_to authors_path
  end
end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController
  def destroy
    @book = BookAuthor.find(params[:id]).book
    BookAuthor.find(params[:id]).destroy
  #  @books = Book.all
    redirect_to @book
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @authors_to_add = Author.all.select {|author| !@book.authors.include?(author)}
    @book_authors = BookAuthor.where(book_id: params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @author_to_add = Author.find(params[:book][:author_ids])
    @book.authors << @author_to_add
    redirect_to @book
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %> </h1>
<% if @author.errors.any? %>
  <ul class="error-list">
    <% @author.errors.full_messages.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_for @author do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %> </p>
  <p><%= f.label :birth_year %>
  <%= f.text_field :birth_year %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/authors/index.html.erb
<h1>Authors!</h1>
<%= link_to "New Author", new_author_path %>
<ul>
  <% @authors.each do |author| %>
    <li>
      <%= link_to author.name, author %> (b. <%= author.birth_year %>)
    </li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>
<% if @author.errors.any? %>
  <ul class="error-list">
    <% @author.errors.full_messages.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_for @author do |f| %>
  <div><%= f.label :name %>
  <%= f.text_field :name %> </div>
  <br>
  <div>

  <%= f.label :birth_year %>
    <%= f.text_field :birth_year %></div>
    <br>
  <%= f.submit %><br>
<% end %>

app/views/authors/show.html.erb
<h1> <%= @author.name %> (b. <%= @author.birth_year %>) </h1>
<span>Books:
<% if @author.books.count == 0 %>
  <em>(none)</em> </span>
  <br>
<% else %>
  <ul>
    <% @books.each do |book| %>
      <li><%= link_to book.title, book %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Edit #{@author.name}", edit_author_path %>
<%= form_tag @author, method: "delete" do %>
  <%= submit_tag "Delete #{@author.name}" %>
<% end %>

app/views/books/index.html.erb
<h1>Books!</h1>
<ul>
  <% @books.each do |book| %>
  <li><%= link_to book.title, book %> (<%= book.pages %> pages)
  <% end %>
  </li>
</ul>

app/views/books/show.html.erb
<h1> <%= @book.title %> (<%= @book.pages %> pages)</h1>
<h2>Authors:</h2>
<ul>
  <% @book_authors.each do |book_author| %>
    <li><%= link_to book_author.author.name_and_birthyear, book_author.author %> <br>
      <%= form_tag book_author, method: "delete" do %>
        <%= submit_tag "Remove author" %>
      <% end %>
    </li>
  <% end %>
</ul>

 <%= form_for @book do |f| %>
  Author <%= f.collection_select :author_ids, @authors_to_add, :id, :name %>
  <%= f.submit "Add author" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title>Devpool’s Rails practice</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <nav>
      <ol>
        <li>
          <%= link_to "Authors Index", authors_path %>
        </li>
        <li>
          <%= link_to "Books Index", books_path %>
        </li>
      </ol>
    </nav>
    <hr/>

        <%= yield %>